### ISSUE TITLE
Question #2 

### ISSUE THREAD

**Issue by kurrent** [nathansmith/javascript-quiz#3]
Why is 0.3 not the result of the following addition? How do you work around this bug?

I would remove or change your wording of calling floating point numbers and the IEEE standard as a "bug"

**Comment by nathansmith** [comment]
Good call. I changed it to "peculiarity" instead of "bug."

https://github.com/nathansmith/javascript-quiz/commit/ff2232934694aa1ee3bed15222e4aea97d96ca32
