### ISSUE TITLE
Question 3: Prototypal inheritance

### ISSUE THREAD

**Issue by nyarly** [nathansmith/javascript-quiz#7]
The feature listed - that properties of the prototype are available to instances - is misleading.  Any class-based OO language that allows for inherited properties to be changed (e.g. Ruby) will exhibit this feature.

The distinction is that class based languages distinguish between the templates and the instances (i.e. classes aren't instances), whereas prototypical languages do not - the "superclass" of a an object is another instance.

**Comment by nathansmith** [comment]
I've clarified that in the answers.md file, thanks! :)
